//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mimeo.DynamicUI.Demo.Avalonia {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mimeo.DynamicUI.Demo.Avalonia.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property 1.
        /// </summary>
        internal static string advancedsubviewmodel_property1 {
            get {
                return ResourceManager.GetString("advancedsubviewmodel_property1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property 2.
        /// </summary>
        internal static string advancedsubviewmodel_property2 {
            get {
                return ResourceManager.GetString("advancedsubviewmodel_property2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub List.
        /// </summary>
        internal static string advancedsubviewmodel_sublist {
            get {
                return ResourceManager.GetString("advancedsubviewmodel_sublist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string advancedsubviewmodel_sublist_header {
            get {
                return ResourceManager.GetString("advancedsubviewmodel_sublist_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Inline Search.
        /// </summary>
        internal static string demogridoptionsviewmodel_useinlinesearch {
            get {
                return ResourceManager.GetString("demogridoptionsviewmodel_useinlinesearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled, the Radzen data grid UI will be used for filtering. If disabled, filters will be specified individually outside of the table..
        /// </summary>
        internal static string demogridoptionsviewmodel_useinlinesearch_desc {
            get {
                return ResourceManager.GetString("demogridoptionsviewmodel_useinlinesearch_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option 2.
        /// </summary>
        internal static string option2languagekey {
            get {
                return ResourceManager.GetString("option2languagekey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property 1.
        /// </summary>
        internal static string simplesubviewmodel_property1 {
            get {
                return ResourceManager.GetString("simplesubviewmodel_property1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property 2.
        /// </summary>
        internal static string simplesubviewmodel_property2 {
            get {
                return ResourceManager.GetString("simplesubviewmodel_property2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property 1.
        /// </summary>
        internal static string subviewmodel_property1 {
            get {
                return ResourceManager.GetString("subviewmodel_property1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub view models can have property descriptions too!.
        /// </summary>
        internal static string subviewmodel_property1_desc {
            get {
                return ResourceManager.GetString("subviewmodel_property1_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property 2.
        /// </summary>
        internal static string subviewmodel_property2 {
            get {
                return ResourceManager.GetString("subviewmodel_property2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub view models can have property descriptions too!.
        /// </summary>
        internal static string subviewmodel_property2_desc {
            get {
                return ResourceManager.GetString("subviewmodel_property2_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Model List.
        /// </summary>
        internal static string testviewmodel_advancedmodellist {
            get {
                return ResourceManager.GetString("testviewmodel_advancedmodellist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string testviewmodel_color {
            get {
                return ResourceManager.GetString("testviewmodel_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A color picker control.
        /// </summary>
        internal static string testviewmodel_color_desc {
            get {
                return ResourceManager.GetString("testviewmodel_color_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo Box.
        /// </summary>
        internal static string testviewmodel_combobox {
            get {
                return ResourceManager.GetString("testviewmodel_combobox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar to a single-select, but any value can be entered. Unlike single and multi-select, options cannot be translated since the raw value is arbitrary user input..
        /// </summary>
        internal static string testviewmodel_combobox_desc {
            get {
                return ResourceManager.GetString("testviewmodel_combobox_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Form Field.
        /// </summary>
        internal static string testviewmodel_customformfield {
            get {
                return ResourceManager.GetString("testviewmodel_customformfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A demonstration of how to define a custom form field control in the client application..
        /// </summary>
        internal static string testviewmodel_customformfield_desc {
            get {
                return ResourceManager.GetString("testviewmodel_customformfield_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime Offset.
        /// </summary>
        internal static string testviewmodel_datetimeoffset {
            get {
                return ResourceManager.GetString("testviewmodel_datetimeoffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same as DateTime, but internally stored as a DateTimeOffset. Note that time zone information may be coerced to UTC but the value should remain correct..
        /// </summary>
        internal static string testviewmodel_datetimeoffset_desc {
            get {
                return ResourceManager.GetString("testviewmodel_datetimeoffset_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        internal static string testviewmodel_datetimeutc {
            get {
                return ResourceManager.GetString("testviewmodel_datetimeutc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An arbitrary date/time in UTC, but displayed in the user&apos;s local time zone..
        /// </summary>
        internal static string testviewmodel_datetimeutc_desc {
            get {
                return ResourceManager.GetString("testviewmodel_datetimeutc_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        internal static string testviewmodel_decimal {
            get {
                return ResourceManager.GetString("testviewmodel_decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An arbitrary decimal used to demonstrate the decimal form field.
        /// </summary>
        internal static string testviewmodel_decimal_desc {
            get {
                return ResourceManager.GetString("testviewmodel_decimal_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string testviewmodel_description {
            get {
                return ResourceManager.GetString("testviewmodel_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string testviewmodel_enabled {
            get {
                return ResourceManager.GetString("testviewmodel_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Hidden Properties.
        /// </summary>
        internal static string testviewmodel_enablehiddenproperties {
            get {
                return ResourceManager.GetString("testviewmodel_enablehiddenproperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled or disabled, another form field is shown/hidden accordingly.
        /// </summary>
        internal static string testviewmodel_enablehiddenproperties_desc {
            get {
                return ResourceManager.GetString("testviewmodel_enablehiddenproperties_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden String.
        /// </summary>
        internal static string testviewmodel_hiddenstring {
            get {
                return ResourceManager.GetString("testviewmodel_hiddenstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An ordinary string that&apos;s only visible when Enable Hidden Properties is checked.
        /// </summary>
        internal static string testviewmodel_hiddenstring_desc {
            get {
                return ResourceManager.GetString("testviewmodel_hiddenstring_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        internal static string testviewmodel_html {
            get {
                return ResourceManager.GetString("testviewmodel_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string testviewmodel_id {
            get {
                return ResourceManager.GetString("testviewmodel_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique identifier of the test model.
        /// </summary>
        internal static string testviewmodel_id_desc {
            get {
                return ResourceManager.GetString("testviewmodel_id_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.
        /// </summary>
        internal static string testviewmodel_json {
            get {
                return ResourceManager.GetString("testviewmodel_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-model List.
        /// </summary>
        internal static string testviewmodel_modellist {
            get {
                return ResourceManager.GetString("testviewmodel_modellist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of view model displayed in a grid.
        /// </summary>
        internal static string testviewmodel_modellist_desc {
            get {
                return ResourceManager.GetString("testviewmodel_modellist_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Select.
        /// </summary>
        internal static string testviewmodel_multiselect {
            get {
                return ResourceManager.GetString("testviewmodel_multiselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sample multi-select control.
        /// </summary>
        internal static string testviewmodel_multiselect_desc {
            get {
                return ResourceManager.GetString("testviewmodel_multiselect_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string testviewmodel_name {
            get {
                return ResourceManager.GetString("testviewmodel_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable String.
        /// </summary>
        internal static string testviewmodel_nullablestringenabled {
            get {
                return ResourceManager.GetString("testviewmodel_nullablestringenabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A boolean setting that enables or disabled an arbitrary form field, useful for values that are logically nullable or feature-switched.
        /// </summary>
        internal static string testviewmodel_nullablestringenabled_desc {
            get {
                return ResourceManager.GetString("testviewmodel_nullablestringenabled_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string testviewmodel_number {
            get {
                return ResourceManager.GetString("testviewmodel_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An arbitrary integer used to demonstrate the number form field.
        /// </summary>
        internal static string testviewmodel_number_desc {
            get {
                return ResourceManager.GetString("testviewmodel_number_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Model.
        /// </summary>
        internal static string testviewmodel_relatedmodelid {
            get {
                return ResourceManager.GetString("testviewmodel_relatedmodelid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Models.
        /// </summary>
        internal static string testviewmodel_relatedmodelids {
            get {
                return ResourceManager.GetString("testviewmodel_relatedmodelids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative Date.
        /// </summary>
        internal static string testviewmodel_relativedate {
            get {
                return ResourceManager.GetString("testviewmodel_relativedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string testviewmodel_section {
            get {
                return ResourceManager.GetString("testviewmodel_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A group of related form fields, which are actually stored in their own view model..
        /// </summary>
        internal static string testviewmodel_section_desc {
            get {
                return ResourceManager.GetString("testviewmodel_section_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Model List.
        /// </summary>
        internal static string testviewmodel_simplemodellist {
            get {
                return ResourceManager.GetString("testviewmodel_simplemodellist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Select.
        /// </summary>
        internal static string testviewmodel_singleselect {
            get {
                return ResourceManager.GetString("testviewmodel_singleselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sample single-select control.
        /// </summary>
        internal static string testviewmodel_singleselect_desc {
            get {
                return ResourceManager.GetString("testviewmodel_singleselect_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String List.
        /// </summary>
        internal static string testviewmodel_stringlist {
            get {
                return ResourceManager.GetString("testviewmodel_stringlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple list of strings.
        /// </summary>
        internal static string testviewmodel_stringlist_desc {
            get {
                return ResourceManager.GetString("testviewmodel_stringlist_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string testviewmodel_stringlist_header {
            get {
                return ResourceManager.GetString("testviewmodel_stringlist_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string testviewmodel_time {
            get {
                return ResourceManager.GetString("testviewmodel_time", resourceCulture);
            }
        }
    }
}
